### ISSUE TITLE
Jaeger options: inconsistency within all options lists

### ISSUE THREAD

**Issue by Slylele** [freesewing/freesewing.org#644]
There are many options missing on the menu at the right and in the YML file on project side... It seems that list of options is correct on the "options" page as it is the same when you create new personal pattern (= 56 options grouped in 6 categories), but if we look at the summary on the right and on the YML file for translation, some are missing (maybe it's normal on YML as it can be merged with other patterns sentences).
![analyse_options_Jaeger](https://user-images.githubusercontent.com/57619777/78499592-d8b4b800-7751-11ea-8e5b-cb9c288f7617.png)

**Comment by Slylele** [comment]
I just noticed too that links on main options page are broken (page doesn't exist) for each option marked as missing in the right menu...

**Comment by Slylele** [comment]
Maybe related to same kind of issue but on pattern creation, the options category "Advanced" is missing... 
![image](https://user-images.githubusercontent.com/57619777/78500418-84f89d80-7756-11ea-9fe3-a804a6963e30.png)

**Comment by joostdecock** [comment]
This is a bit of a hairy issue :) Allow my to explain the discrepancies:

The options on the left (the main part of the page) come from the `pattern-info` package which in turns gets its data from the configuration of the patterns themselves.
This is the 'real' data.

On the right, we have the hierarchy of documentation. Normally, all options should be documented. When they are not, they will not show up on the right.

Now because often options are the same (typically when patterns inherit each other, eg simon is based on brian) we 'duplicate' the options. But sometimes, we don't pay careful attention and duplicate an option from one pattern into another that shouldn't be duplicated.
In this case, the option will show up on the right, but not the left.

In the short term, I will try to weed out these issues.
In the long(er) term, I hope to have each option documented in the different patterns

**Comment by joostdecock** [comment]
You can check on https://next.freesewing.org/ where I have implemented some changes that should make the options situation better.

**Comment by Slylele** [comment]
Thank you for quick change and all these explanations! I've checked and it seems better!
Just some remarks:
- [ ] 2 options are missing: "Sleeve cap height" (was there before) and "Front pocket radius" (was already missing)
- [ ] there are 4 ghost options...
- [ ] the "Advanced" options are still missing in the creation part of new draft (and I've seen that this category is missing on other patterns as Simon for example)

![image](https://user-images.githubusercontent.com/57619777/78504539-41119280-776e-11ea-9f4d-19e62f146b92.png)

**Comment by joostdecock** [comment]
I seem to have lost track of this issue, but this was fixed a while back. All options are now available.

>  the "Advanced" options are still missing in the creation part of new draft (and I've seen that this category is missing on other patterns as Simon for example)

The *advanced* options are a special case. They are only shown when you enable *Expert mode* under the pattern options. But when you do, they are there.
